astra_db:
  collection_name: "chatbot_ecomm"

embedding_models:
  provider: "openai"
  model_name: "text-embedding-3-small"

retriever:
  top_k: 3

llm:
  provider: "openai"
  model_name: "gpt-4.1-mini"